[package]
name = "deskpet"
version = "0.3.2"
edition = "2021"

[dependencies]
winit = "0.30"
softbuffer = "0.4"
fontdue = "0.9"
png = "0.17"
raw-window-handle = "0.6"
ureq = { version = "2", features = ["json"] }
rustls = { version = "0.23", features = ["ring"] }
serde_json = "1"
toml = "0.8"
base64 = "0.22"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Dwm",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_XboxController",
    "Win32_Media_Audio",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
    "Win32_Security",
] }
tray-icon = "0.25"

[profile.release]
opt-level = "z"
lto = false
codegen-units = 1
strip = true
panic = "abort"
